# Examen

La idea de este notebook es utilizarlo para revisar qué opciones distintas tenemos para el examen de módulo 3 de TC1003B: álgebra lineal.

In [1]:
import numpy as np
from scipy import linalg

## Figura 1

¿Cuántas entradas tiene la red? `4`

¿Cuántos pesos tiene la red? `4`

¿Cuántas neuronas tiene la red? `1`

¿Cuántas funciones de activación tiene la red? `1`

¿Cuántas salidas tiene la red? `1`

## Figura 2

¿Cuántas entradas tiene la red? $R$

¿Cuántos pesos tiene la red? $S \times R$

¿Cuántas neuronas tiene la red?  $S$

¿Cuántas funciones de activación tiene la red? $S$

¿Cuántas salidas tiene la red? $S$

## Estructuras de datos

Las estructuras de datos deben ser:

1. Vector de entradas $\mathbf{p} = \begin{bmatrix} p_1 & p_2 & \dots & p_R\end{bmatrix}^T$

2. Matriz de pesos $W = \begin{bmatrix}
W_{11} & W_{12} & \dots & W_{1R} \\
W_{21} & W_{22} & \dots & W_{2R} \\
\vdots & \ddots & \ddots& \vdots \\
W_{S1} & W_{S2} & \dots & W_{SR}
\end{bmatrix}$

3. Vector de sesgos $\mathbf{b} = \begin{bmatrix} b_1 & b_2 & \dots & b_S\end{bmatrix}^T$

4. Vector de funciones de activación $\mathbf{f} = \begin{bmatrix} f_1 & f_2 & \dots & f_S \end{bmatrix}^T$
5. Vector de salidas $\mathbf{a} = \begin{bmatrix} a_1 & a_2 & \dots & a_S \end{bmatrix}^T$

## SEL

In [2]:
P = np.array([[3, 6, -9],
              [2, 4, -8],
              [-2, -3, 4],
              [4, 3, -7],
             [5, 4, -9],
             [7, 7, -13],
             [-2, -5, 9],
             [-1, 6, 2]])
t = np.array([3, 0, -1, -6, -7, -6, -2, 22])

In [3]:
W0 = np.array([[1, 2, 2],
               [2, 3, 1],
               [4, 2, 2],
               [3, 0, 2]])

W1 = np.array([[2, 2, 0],
               [2, 1, 1],
               [3, 2, 2],
               [5, 2, 4],
               [1, 2, 0]])
b0 = np.array([[1], [2], [-1], [1]])
b1 = np.array([[-1], [0], [0], [2], [-1]])

In [8]:
P.transpose()

array([[  3,   2,  -2,   4,   5,   7,  -2,  -1],
       [  6,   4,  -3,   3,   4,   7,  -5,   6],
       [ -9,  -8,   4,  -7,  -9, -13,   9,   2]])

In [4]:
def solve_team(A, t, W, b):
    print(f"Solution is {linalg.solve(A,t)}")
    print(f"a = \n{np.matmul(W,np.transpose(P)) + b}")

In [11]:
np.matmul(W0,P.transpose())

array([[ -3,  -6,   0,  -4,  -5,  -5,   6,  15],
       [ 15,   8,  -9,  10,  13,  22, -10,  18],
       [  6,   0,  -6,   8,  10,  16,   0,  12],
       [ -9, -10,   2,  -2,  -3,  -5,  12,   1]])

In [6]:
# Equipo 4
solve_team(np.vstack((P[3], P[6:8])), np.hstack((t[3], t[6:8])), W0, b0)
# they mis-copied so here it is as if they were working with the right numbers
A = np.vstack((P[3], np.array([2, -5, 9]), P[7]))
b = np.hstack((t[3], t[6], t[7]))
print(linalg.solve(A,b))
print(f'{-38/43}, {128/43}, {70/43}')

Solution is [-2.  3.  1.]
a = 
[[-2 -5  1 -3 -4 -4  7 16]
 [17 10 -7 12 15 24 -8 20]
 [ 5 -1 -7  7  9 15 -1 11]
 [-8 -9  3 -1 -2 -4 13  2]]
[-0.88372093  2.97674419  1.62790698]
-0.8837209302325582, 2.9767441860465116, 1.627906976744186


In [7]:
# Equipo 7

solve_team(P[2:5], t[2:5], W1, b1)

Solution is [-2.  3.  1.]
a = 
[[ 17  11 -11  13  17  27 -15   9]
 [  3   0  -3   4   5   8   0   6]
 [  3  -2  -4   4   5   9   2  13]
 [ -7 -12   2   0  -1  -1  18  17]
 [ 14   9  -9   9  12  20 -13  10]]


In [15]:
# Equipo 1
solve_team(np.vstack((P[0], P[1], P[4])), np.hstack((t[0], t[1], t[4])), W1, b1)

Solution is [-2.  3.  1.]
a = 
[[ 17  11 -11  13  17  27 -15   9]
 [  3   0  -3   4   5   8   0   6]
 [  3  -2  -4   4   5   9   2  13]
 [ -7 -12   2   0  -1  -1  18  17]
 [ 14   9  -9   9  12  20 -13  10]]


In [17]:
solve_team(P[0:3],t[0:3], W1, b1)

Solution is [-2.  3.  1.]
a = 
[[ 17  11 -11  13  17  27 -15   9]
 [  3   0  -3   4   5   8   0   6]
 [  3  -2  -4   4   5   9   2  13]
 [ -7 -12   2   0  -1  -1  18  17]
 [ 14   9  -9   9  12  20 -13  10]]


In [32]:
A = P[0:3]
A = np.hstack((A, np.array([[3], [0], [-1]])))
A

array([[ 3,  6, -9,  3],
       [ 2,  4, -8,  0],
       [-2, -3,  4, -1]])

In [33]:
A[0] = A[0] /3
A[1] = A[1] - 2*A[0]
A

array([[ 1,  2, -3,  1],
       [ 0,  0, -2, -2],
       [-2, -3,  4, -1]])

In [34]:
A[2] = A[2] + 2 * A[0]
A

array([[ 1,  2, -3,  1],
       [ 0,  0, -2, -2],
       [ 0,  1, -2,  1]])