# Sistemas de ecuaciones lineales en Python

## Sympy: programación simbólica en Python

`sympy` es un módulo de programación simbólica para Python que te permite utilizar variables como símbolos matemáticos y no como datos.

### Programación simbólica

Al declarar `x=5`, estamos haciendo una asignación&mdash; el valor 5 se está asignando a `x`.

Si quisiéramos calcular  `x ** 2`, entonces Python normalmente nos devolvería `25`, pues es el cuadrado de su valor original, `5`.

Con programación simbólica, en lugar de pensar en un valor, pensamos en una variable: `x ** 2` es $x^2$, independientemente del valor de `x`. Es hasta que decidimos _evaluar_ el valor de $x^2$ que obtenemos el resultado: `25`.

### Ecuaciones lineales con `sympy`

`sympy` tiene también algunas herramientas para ecuaciones lineales.
Podemos dar de alta un sistema de ecuaciones lineales para intentar resolverlo directamente de la siguiente manera:

Del módulo `sympy` importamos específicamente las funciones `symbols` y `linsolve`, y la clase `Matrix`:

In [2]:
from sympy import symbols, Matrix, linsolve

Damos de alta el sistema con una matriz de coeficientes y un vector de constantes

In [2]:
x, y, z = symbols('x, y, z')
A = Matrix([[3, 2, 4], [2, 2, 2], [4, 4, 3]])
b = Matrix([[270], [200], [375]])

Y revisamos el valor de $A$ y $\mathbf{b}$

In [3]:
A

Matrix([
[3, 2, 4],
[2, 2, 2],
[4, 4, 3]])

In [4]:
b

Matrix([
[270],
[200],
[375]])

Para terminar, resolvemos el sistema usando `linsolve`

In [6]:
linsolve((A,b),[x, y, z])

{(20, 55, 25)}

que nos devuelve un conjunto de las posibles soluciones. En este caso, sólo hay una posible solución, que es $(20, 55, 25)$, que es una *tupla*: un grupo de datos de tamaño fijo donde el orden importa. En este caso, $x_1 = 20, \; x_2 = 55 \;$ y $x_3 = 25$

## Scipy: librería científica para Python

`scipy` es un módulo de Python que contiene herramientas para *ciencia*: pruebas estadísticas, análisis de señales, álgebra lineal, optimización e integración.

Este módulo va de la mano con `numpy`, que es otro módulo que utilizamos comúnmente para cálculo numérico.

Importamos `numpy` como `np` y de `scipy` importamos el módulo de álgebra lineal

In [3]:
import numpy as np
from scipy import linalg

Damos de alta el sistema usando arreglos de `numpy`, tanto para la matriz de coeficientes como para el vector de constantes

In [8]:
A = np.array([[3, 2, 4], [2, 2, 2], [4, 4, 3]])
b = np.array([270, 200, 375])

Revisamos que esté todo en orden

In [9]:
A

array([[3, 2, 4],
       [2, 2, 2],
       [4, 4, 3]])

In [10]:
b

array([270, 200, 375])

y usamos la función `solve` del módulo `linalg` para resolver el sistema

In [7]:
linalg.solve(A, b)

array([20., 55., 25.])

la función `solve` regresa un arreglo de las soluciones (donde el orden importa): $x_1 = 20, \; x_2 = 55 \,$ y $x_3 = 25$